CLEAN_DROP_FIELDS:
  - 'Protein Length'
  - 'Sequence'
  - 'Enrichment'
  - 'Accesion Number'
  - 'Protein Abundance'
CLEAN_ENRICHMENT_SPLIT_VALUE: 1
CLEAN_MASK_PATH: '/Users/mct19/repos/ENM-Protein-Predictor/Input_Files/mask-payne-2021_04_28T15:11:1619637102.csv'
INIT_DATA_PATH: '/Users/mct19/repos/ENM-Protein-Predictor/Input_Files/KarstenChanData.csv'
MODEL_BOOTSTRAP: True
MODEL_NUM_TREES: 1000
MODEL_MIN_SAMPLE_SPLIT: 2
MODEL_MAX_FEATURES: 'auto'
MODEL_MAX_DEPTH: 5
MODEL_CRITERION: 'entropy'
MODEL_NUM_JOBS: -1
TRAIN_SPLIT_PERCENTAGE: 0.60