CLEAN_DROP_FIELDS:
  - 'Protein Length'
  - 'Sequence'
  - 'Enrichment'
  - 'Accesion Number'
  - 'Protein Abundance'
CLEAN_ENRICHMENT_SPLIT_VALUE: 1
CLEAN_MASK_PATH: '/Users/mct19/repos/ENM-Protein-Predictor/Input_Files/mask-payne-2021_04_28T14:27:1619634423.csv'
INIT_DATA_PATH: '/Users/mct19/repos/ENM-Protein-Predictor/Input_Files/KarstenChanData.csv'
MODEL_BOOTSTRAP: True
MODEL_ESTIMATOR_COUNT: 1000
MODEL_MIN_SAMPLE_SPLIT: 4
MODEL_NUM_JOBS: -1
TRAIN_SPLIT_PERCENTAGE: 0.60