CLEAN_DROP_FIELDS:
  - 'Protein Length'
  - 'Sequence'
  - 'Enrichment'
  - 'Accesion Number'
  - 'Protein Abundance'
CLEAN_ENRICHMENT_SPLIT_VALUE: 1
CLEAN_MASK_PATH: 'data-in/mask-payne-2021_04_28T15:41:1619638865.csv'
CLEAN_TARGET_FIELDNAME: 'Enrichment'
INIT_DATA_PATH: 'data-in/KarstenChanData.csv'
MODEL_BOOTSTRAP: True
MODEL_NUM_TREES: 2500
MODEL_MIN_SAMPLE_SPLIT: 5
MODEL_MAX_FEATURES: 'sqrt'
MODEL_MAX_DEPTH: 5
MODEL_CRITERION: 'entropy'
MODEL_NUM_JOBS: -1
MODEL_PERSIST:
  PERSIST: True
  PERSIST_PATH: 'data-out/persisted-model.pickle'
TRAIN_METRICS_WRITE_PATH: 'data-out/pipeline-out-payne.json'
TRAIN_SPLIT_PERCENTAGE: 0.60
VALIDATION_PROBABLITY_THRESHOLD: 0.5