CLEAN_DROP_FIELDS:
  - 'Protein Length'
  - 'Sequence'
  - 'Enrichment'
  - 'Accesion Number'
  - 'Protein Abundance'
CLEAN_ENRICHMENT_SPLIT_VALUE: 1
CLEAN_MASK_PATH: 'data-in/mask-payne-2021_04_28T15:41:1619638865.csv'
CLEAN_TARGET_FIELDNAME: 'Enrichment'
INIT_DATA_PATH: 'data-in/KarstenChanData.csv'
MODEL_BOOTSTRAP: True
MODEL_NUM_TREES: 1000
MODEL_MIN_SAMPLE_SPLIT: 2
MODEL_MAX_FEATURES: 'auto'
MODEL_MAX_DEPTH: 5
MODEL_CRITERION: 'entropy'
MODEL_NUM_JOBS: -1
OPT_BEST_PARAMS_WRITE_PATH: 'data-out/best-params-payne.yml'
OPT_NUM_FOLDS: 5
OPT_NUM_TREES_GRID:
  - 500
OPT_MAX_FEATURES_GRID:
  - 'auto'
  - 'sqrt'
  - 'log2'
OPT_MAX_DEPTH_GRID:
  - 5
OPT_MIN_SAMPLES_SPLIT_GRID:
  - 2
OPT_CRITERION_GRID:
  - 'gini'
  - 'entropy'