CLEAN_DROP_FIELDS:
  - 'Protein Length'
  - 'Sequence'
  - 'Enrichment'
  - 'Accesion Number'
  - 'Protein Abundance'
CLEAN_ENRICHMENT_SPLIT_VALUE: 1
CLEAN_TARGET_FIELDNAME: 'Enrichment'
INIT_DATA_PATH: '/Users/mct19/repos/ENM-Protein-Predictor/Input_Files/KarstenChanData.csv'
MODEL_BOOTSTRAP: True
MODEL_NUM_TREES: 1000
MODEL_MIN_SAMPLE_SPLIT: 2
MODEL_MAX_FEATURES: 'auto'
MODEL_MAX_DEPTH: 5
MODEL_CRITERION: 'entropy'
MODEL_NUM_JOBS: -1
RFECV_MIN_FEATURES: 3
RFECV_NUM_FOLDS: 3
RFECV_SCORING: 'f1'
RFECV_STEP: 1